### ISSUE TITLE
Broken links in `Deploying a New Workflow` section

### ISSUE THREAD

**Issue by gciavarrini** [apache/incubator-kie-kogito-docs#468]
In [Deploying a New Workflow](https://sonataflow.org/serverlessworkflow/main/cloud/operator/developing-workflows.html#_deploying_a_new_workflow) section, there are two broken links:

> Deploying the greeting Workflow example
>
> `kubectl apply -f https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/main/test/testdata/sw.kogito_v1alpha08_sonataflow_devmode.yaml -n <your_namespace>`

The link should be replaced with `https://github.com/kiegroup/kogito-serverless-operator/blob/main/test/testdata/sonataflow.org_v1alpha08_sonataflow_devmode.yaml`

At the end of the same section, there is a similar issue with 

> For example using VSCode, there are the commands needed:
>
> curl -S https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/main/config/samples/sw.kogito_v1alpha08_sonataflow_devmode.yaml > workflow_devmode.yaml
>code workflow_devmode.yaml
> kubectl apply -f workflow_devmode.yaml -n <your_namespace>

In this case, there is no `sonataflow.org_v1alpha08_sonataflow_devmode.yaml` in `/config/samples` folder. Since the guide require `sonataflow.org/profile: dev` the only applicable config seems to be [sonataflow.org_v1alpha08_sonataflow_devmodeWithConfigMapAndExternalResource.yaml](https://github.com/kiegroup/kogito-serverless-operator/blob/main/config/samples/sonataflow.org_v1alpha08_sonataflow_devmodeWithConfigMapAndExternalResource.yaml)
Is it correct?

I'd be happy to open a PR to fix this, but I need a bit of guidance here :)

**Comment by ricardozanini** [comment]
Hi @gciavarrini many thanks for reporting it! Can you send a PR? It's pretty straightforward. Here are the files: https://github.com/kiegroup/kogito-docs/tree/main/serverlessworkflow/modules/ROOT/pages

**Comment by MarianMacik** [comment]
Fixed in #500.
