### ISSUE TITLE
Keep only Postgres references to the docs

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-docs#525]
We have to remove references from Infinispan, MongoDB, and Oracle (everything that's not Postgres) from our documentation since we are not distributing these images anymore.

**Comment by ricardozanini** [comment]
@nmirasch @wmedvede maybe opening an issue on examples too.

**Comment by domhanak** [comment]
I can remove them in  #536,  already noticed them and have a todo there. LMK what you prefer

**Comment by ricardozanini** [comment]
Feel free to do what's easier for you!

**Comment by domhanak** [comment]
Assigned myself

**Comment by domhanak** [comment]
Resolved by https://github.com/apache/incubator-kie-kogito-docs/pull/636
