### ISSUE TITLE
Holistic review of non-quarkus getting-started chapter

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-docs#583]
**Goal**
Holistic review of non-quarkus [getting-started](https://sonataflow.org/serverlessworkflow/main/use-cases/advanced-developer-use-cases/getting-started/create-your-first-workflow-service.html)

**Comment by domhanak** [comment]
@LuboTerifaj I think I pasted wrong link here - should be what is in -> https://sonataflow-docs-preview-pr-605.surge.sh/serverlessworkflow/latest/getting-started/getting-familiar-with-our-tooling.html and same lvl chapters. Apologies

**Comment by LuboTerifaj** [comment]
@domhanak there is a different issue reported for tooling part here: https://github.com/apache/incubator-kie-kogito-docs/issues/590. Why is the getting started link wrong?

**Comment by domhanak** [comment]
@LuboTerifaj  The link here point to quarkus section, this is non-quarkus.
Getting-familair-with-our-tooling is part of getting started not tooling
