### ISSUE TITLE
Holistic review of non-quarkus service orchestration chapter

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-docs#591]
**Goal**
Holistic review of non-quarkus [service orchestration chapter](https://sonataflow.org/serverlessworkflow/main/service-orchestration/orchestration-of-openapi-based-services.html)

**Comment by LuboTerifaj** [comment]
I found many issues during the review. I provided some fixes in https://github.com/apache/incubator-kie-kogito-docs/pull/660 . The remaining issues are reported here:

- https://github.com/apache/incubator-kie-kogito-docs/issues/657
- https://github.com/apache/incubator-kie-kogito-docs/issues/658
- https://github.com/apache/incubator-kie-kogito-docs/issues/659
