### ISSUE TITLE
Holistic review of non-quarkus executing, testing and troubleshooting chapter

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-docs#594]
**Goal**
Holistic review of non-quarkus [Executing, Testing and Troubleshooting chapter](https://sonataflow.org/serverlessworkflow/main/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-overview.html)

**Comment by LuboTerifaj** [comment]
I found several issues. I provided two fixes in https://github.com/apache/incubator-kie-kogito-docs/pull/655 . I reported remaining issues here:

- https://github.com/apache/incubator-kie-kogito-docs/issues/652
- https://github.com/apache/incubator-kie-kogito-docs/issues/653
- https://github.com/apache/incubator-kie-kogito-docs/issues/654
