### ISSUE TITLE
Restructuring of the Cloud -> Operator -> Persistence chapter

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-docs#608]
Review the Cloud > Operator > Persistence guide:

- The guide is updated to the latest SonataFlow CRC and SonataFlowPlatform CRD definitions.
- Scenarios of "preview" an "gitops" are covered
- Database schema initialization is covered
- any other.

**Comment by ricardozanini** [comment]
@wmedvede I guess you did this one already?

**Comment by wmedvede** [comment]
@ricardozanini more or less, but I'm still working here, since I have found out-dated bits in the SonataFlowPlatform persistence configuration parts of the guide. So I'm  using this issue to do several updates in the operator managed persistence section.
