### ISSUE TITLE
Document adding a CA to a workflow

### ISSUE THREAD

**Issue by rgolangh** [apache/incubator-kie-kogito-docs#610]
Document how to add a CA into the default java truststore.

This is needed for workflows that orchestrate system with private CA's or just a self signed one.
The document will show how to add the kubernetes root CA to a simple pod and also to a SonataResource

**Comment by rgolangh** [comment]
@ricardozanini please guide me under which directory to put the guide?

**Comment by ricardozanini** [comment]
Sure thing! I think you can add a new guide under Cloud > Operators: https://sonataflow.org/serverlessworkflow/main/cloud/index.html
