### ISSUE TITLE
Emoji icons are not loaded in the documentation 

### ISSUE THREAD

**Issue by tomasdavidorg** [apache/incubator-kie-kogito-docs#619]
If you take a look on the page https://sonataflow.org/serverlessworkflow/main/core/cncf-serverless-workflow-specification-support.html, the emoji icons are not loaded.
![image](https://github.com/apache/incubator-kie-kogito-docs/assets/4498639/b009b37d-cf91-4565-8997-e79df6c67672)

**Comment by ricardozanini** [comment]
@tomasdavidorg can you send a PR to solve it?

**Comment by tomasdavidorg** [comment]
@ricardozanini I or @barboras7 will take a look. For now I will assign it to myself.
