### ISSUE TITLE
Create a new SonataFlow guide for Knative Eventing Integration with Jobs Service and Data Index

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-docs#627]
In this task, we will create a new guide helping users to integrate workflows, Data Index, and Jobs Services applications with Knative Eventing.

These services already support communication via HTTP CloudEvents. Users can create SinkBindings and Triggers to make these services communicate via events.

In this guide, we will instruct users to create these objects and make the architecture available in the cluster. A viable example can be seen here: https://github.com/flows-examples/techpreview2/tree/main/platforms/data_index_and_jobservice_as_platform_service_postgresql_persistence_knative_eventing_manual

In future versions, the operator will manage these objects automatically.

**Comment by fjtirado** [comment]
Is not that already explained (at least for jobs service) here? https://sonataflow.org/serverlessworkflow/latest/job-services/quarkus-extensions.html#kogito-addons-quarkus-jobs-knative-eventing

**Comment by wmedvede** [comment]
@fjtirado this explanation is good, but, don't consider a full operator managed deployment, where, the WF, DI and JS deployments, configurations, etc, are fully operator managed.
So the user will have to do manual configurations.

The need for this guide is a consequence of https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/438 not being completed.
