### ISSUE TITLE
Clarify usage of `from` and `to` in Data Index GraphQL endpoint documentation

### ISSUE THREAD

**Issue by gciavarrini** [apache/incubator-kie-kogito-docs#678]
The [Data Index GraphQL endpoint](https://sonataflow.org/serverlessworkflow/main/data-index/data-index-core-concepts.html#data-index-graphql) currently lists the following operators for `Number` and `Date`:
```adoc
* between: Numeric range
* from: Integer
* to: Integer
```
and 
```adoc
* between: Date range
* from: Date time
* to: Date time
```

However, `from` and `to` are not standalone operators. They should only be used as part of the `between` operator.

To improve clarity, I propose updating the documentation as follows:
```adoc
* `between`: Date range (with `from` and `to` values required)
```
and 
```adoc
* `between`: Numeric range (with `from` and `to` values required)
```

**Comment by domhanak** [comment]
Resolved by #680
